// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCdjQOOMEm3fzapvHX4a3V2ZBFFEMH_Ys',
    appId: '1:941278245703:web:b3c6616ec8f2cc681a1262',
    messagingSenderId: '941278245703',
    projectId: 'pixcamprod',
    authDomain: 'pixcamprod.firebaseapp.com',
    storageBucket: 'pixcamprod.appspot.com',
    measurementId: 'G-YTN4RZJW51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpbcbdVeNkeqizDnO87S5LwFReGYc9_Hw',
    appId: '1:941278245703:android:fc3aa23c90c6f0f91a1262',
    messagingSenderId: '941278245703',
    projectId: 'pixcamprod',
    storageBucket: 'pixcamprod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXkvp81pnM61LLwcxHIlGfk5ofaJeJyTw',
    appId: '1:941278245703:ios:0dbd90019d26a6e41a1262',
    messagingSenderId: '941278245703',
    projectId: 'pixcamprod',
    storageBucket: 'pixcamprod.appspot.com',
    iosClientId: '941278245703-brrmvdio87g9gori3b387kdibgqttklm.apps.googleusercontent.com',
    iosBundleId: 'com.pixelbrahma.pix-cam',
  );
}
