// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCckYCDI19aX93IHiFNQlecugtgZTG8gUM',
    appId: '1:343839518483:web:21b92d69e02048915934e6',
    messagingSenderId: '343839518483',
    projectId: 'pixcam',
    authDomain: 'pixcam.firebaseapp.com',
    storageBucket: 'pixcam.appspot.com',
    measurementId: 'G-344HKX9470',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA17sm5wBhbIV0I-mLP0Lcddwda_Y6TXNY',
    appId: '1:343839518483:android:106a80efedffdc055934e6',
    messagingSenderId: '343839518483',
    projectId: 'pixcam',
    storageBucket: 'pixcam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkR3_dt9VXeRC7P1WOti10FFCnhsejn1Q',
    appId: '1:343839518483:ios:40e9ec27f87543415934e6',
    messagingSenderId: '343839518483',
    projectId: 'pixcam',
    storageBucket: 'pixcam.appspot.com',
    iosClientId: '343839518483-bva9iloktphg15ouebul6v8ukrc4l21q.apps.googleusercontent.com',
    iosBundleId: 'com.pixelbrahma.pix-cam.dev',
  );
}
